### ISSUE TITLE
Rubyripper is broken with Ruby 1.9.3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bleskodev/rubyripper#503]
```
1) After upgrading Ruby from 1.9.2 to 1.9.3, RubyRipper fails to start.

2) When starting rrip_gui via terminal, I get the following output:

"/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be 
deprecated in the future, use String#encode instead.
/usr/lib/ruby/gems/1.9.1/gems/gettext-2.1.0/lib/gettext/runtime/locale_path.rb:2
0: Use RbConfig instead of obsolete and deprecated Config.
NOTE: Gem.all_load_paths is deprecated with no replacement. It will be removed 
on or after 2011-10-01.
Gem.all_load_paths called from 
/usr/lib/ruby/gems/1.9.1/gems/gettext-2.1.0/lib/gettext/runtime/locale_path.rb:5
6.
NOTE: Gem.all_partials is deprecated with no replacement. It will be removed on 
or after 2011-10-01.
Gem.all_partials called from /usr/lib/ruby/1.9.1/rubygems.rb:258.
/usr/lib/ruby/1.9.1/rubygems.rb:259:in `block (2 levels) in all_load_paths': 
undefined method `add' for "/usr/lib/ruby/gems/1.9.1":String (NoMethodError)
    from /usr/lib/ruby/1.9.1/rubygems.rb:427:in `block (2 levels) in each_load_path'
    from /usr/lib/ruby/1.9.1/rubygems.rb:426:in `each'
    from /usr/lib/ruby/1.9.1/rubygems.rb:426:in `block in each_load_path'
    from /usr/lib/ruby/1.9.1/rubygems.rb:421:in `each'
    from /usr/lib/ruby/1.9.1/rubygems.rb:421:in `each_load_path'
    from /usr/lib/ruby/1.9.1/rubygems.rb:258:in `block in all_load_paths'
    from /usr/lib/ruby/1.9.1/rubygems.rb:257:in `each'
    from /usr/lib/ruby/1.9.1/rubygems.rb:257:in `all_load_paths'
    from /usr/lib/ruby/1.9.1/rubygems/deprecate.rb:63:in `block (2 levels) in deprecate'
    from /usr/lib/ruby/gems/1.9.1/gems/gettext-2.1.0/lib/gettext/runtime/locale_path.rb:56:in `default_path_rules'
    from /usr/lib/ruby/gems/1.9.1/gems/locale-2.0.5/lib/locale/util/memoizable.rb:80:in `block in default_path_rules'
    from /usr/lib/ruby/gems/1.9.1/gems/locale-2.0.5/lib/locale/util/memoizable.rb:95:in `block in _memoize_dup'
    from /usr/lib/ruby/gems/1.9.1/gems/locale-2.0.5/lib/locale/util/memoizable.rb:87:in `_memoize'
    from /usr/lib/ruby/gems/1.9.1/gems/locale-2.0.5/lib/locale/util/memoizable.rb:95:in `_memoize_dup'
    from /usr/lib/ruby/gems/1.9.1/gems/locale-2.0.5/lib/locale/util/memoizable.rb:79:in `default_path_rules'
    from /usr/lib/ruby/gems/1.9.1/gems/gettext-2.1.0/lib/gettext/runtime/locale_path.rb:84:in `initialize'
    from /usr/lib/ruby/gems/1.9.1/gems/gettext-2.1.0/lib/gettext/runtime/textdomain.rb:60:in `new'
    from /usr/lib/ruby/gems/1.9.1/gems/gettext-2.1.0/lib/gettext/runtime/textdomain.rb:60:in `initialize'
    from /usr/lib/ruby/gems/1.9.1/gems/gettext-2.1.0/lib/gettext/runtime/textdomain_manager.rb:208:in `new'
    from /usr/lib/ruby/gems/1.9.1/gems/gettext-2.1.0/lib/gettext/runtime/textdomain_manager.rb:208:in `create_or_find_textdomain'
    from /usr/lib/ruby/gems/1.9.1/gems/gettext-2.1.0/lib/gettext/runtime/textdomain_manager.rb:69:in `bind_to'
    from /usr/lib/ruby/gems/1.9.1/gems/gettext-2.1.0/lib/gettext.rb:83:in `bindtextdomain_to'
    from /usr/lib/ruby/gems/1.9.1/gems/gettext-2.1.0/lib/gettext.rb:64:in `bindtextdomain'
    from /usr/lib/ruby/site_ruby/1.9.1/rr_lib.rb:27:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/bin/rrip_gui:24:in `block in <main>'
    from /usr/bin/rrip_gui:22:in `each'
    from /usr/bin/rrip_gui:22:in `<main>'
"

3) This happens on Arch (i686) with RubyRipper 0.6.2-1.

4) Tried with the latest Version from code.google.com, it's the same here.

```

Original issue reported on code.google.com by `thorsten...@gmail.com` on 15 Dec 2011 at 3:11
